apiVersion: v1
kind: Service
metadata:
  name: helloflex
  namespace: hello
  labels:
    app: helloflex
    service: helloflex
spec:
  ports:
    - port: 5000
      name: http
  selector:
    app: helloflex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloflex
  namespace: hello
  labels:
    app: helloflex
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloflex
      version: v1
  template:
    metadata:
      labels:
        app: helloflex
        version: v1
      annotations:
        sidecar.istio.io/componentLogLevel: "lua:debug"
    spec:
      containers:
        - name: helloflex
          env:
            - name: SERVICE_VERSION
              value: v1
          image: docker.io/istio/examples-helloworld-v1
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: helloflex
  namespace: hello
spec:
  hosts:
    - helloflex
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: helloflex.hello.svc.cluster.local
            port:
              number: 5000
---

