apiVersion: v1
kind: Namespace
metadata:
  name: flex
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
